// <auto-generated/>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "Domain term", Scope = "type", Target = "~T:Mmu.Wss.Application.Areas.Common.Models.Option`1")]
[assembly: SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "Domain term", Scope = "type", Target = "~T:Mmu.Wss.Application.Areas.Common.Models.Option")]